### ISSUE TITLE
[feat] Quick play recommendations

### ISSUE THREAD

**Issue by bobbymannino** [Rawnly/raycast-music#3]
It would be a nice feature to be able to quick play the recommendations from within raycast, i dont know how the api is set up so it might not be possible but if it could would save having to open music etc.

**Comment by rawnly** [comment]
Unfortunately the only way I can reproduce are tracks. This is because the actual "play" action has to be performed via AppleScript and what I'm currently doing is searching in the user library for a matching title 🥲 kinda tricky but seem to work most of the times. 

This is also how it works the status bar player (but reversed)

**Comment by rawnly** [comment]
MusicKit js is limited to browser environments and IDs from api and AppleScript are totally different.

**Comment by bobbymannino** [comment]
Makes sense yeah, happy to close if you are
